# GitHub Action for building a LaTeX document
name: Build LaTeX CV

# Trigger condition: Runs whenever code is pushed to the main branch.
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    # ------------------ ADD THIS PERMISSIONS BLOCK ------------------
    permissions:
      contents: write # This gives the action permission to push to your repository
    # --------------------------------------------------------------
    
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Step 2: Compile the LaTeX document into a PDF
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: xelatex

      # Step 3: Commit the generated PDF file back to your repository
      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: Automatically build and update CV PDF"
          file_pattern: main.pdf
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
